//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOET_HMI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CHP_HMIEntities : DbContext
    {
        public CHP_HMIEntities()
            : base("name=CHP_HMIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<db_actual> db_actual { get; set; }
        public virtual DbSet<db_config> db_config { get; set; }
        public virtual DbSet<db_manuallog> db_manuallog { get; set; }
        public virtual DbSet<db_message> db_message { get; set; }
        public virtual DbSet<db_orderarchiv> db_orderarchiv { get; set; }
        public virtual DbSet<db_orderqueue> db_orderqueue { get; set; }
        public virtual DbSet<db_parameter> db_parameter { get; set; }
        public virtual DbSet<db_parameterlog> db_parameterlog { get; set; }
        public virtual DbSet<db_paramset> db_paramset { get; set; }
        public virtual DbSet<db_project> db_project { get; set; }
        public virtual DbSet<db_user> db_user { get; set; }
        public virtual DbSet<db_userlevel> db_userlevel { get; set; }
        public virtual DbSet<db_userlog> db_userlog { get; set; }
    }
}
