//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOET_HMI
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_actual
    {
        public int id { get; set; }
        public int iTypeparamSetID { get; set; }
        public int iMachineparamSetID { get; set; }
        public int iManualParamSetId { get; set; }
        public int iOrderStartMode { get; set; }
    }
}
