//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOET_HMI
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_message
    {
        public long id { get; set; }
        public string sMessage { get; set; }
        public System.DateTime dtCome { get; set; }
        public Nullable<System.DateTime> dtGone { get; set; }
        public Nullable<System.DateTime> dtQuit { get; set; }
        public int iType { get; set; }
        public string sUserName { get; set; }
        public string sStation { get; set; }
        public string sBMK { get; set; }
        public bool bActive { get; set; }
        public int iModul { get; set; }
    }
}
