//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOET_HMI
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_orderqueue
    {
        public long id { get; set; }
        public int iParamSetId { get; set; }
        public int iNrInQueue { get; set; }
        public int iQuantity { get; set; }
        public int iCartonQuantProPallet { get; set; }
        public string sAddedBy { get; set; }
        public System.DateTime dtAddedOn { get; set; }
    
        public virtual db_paramset db_paramset { get; set; }
    }
}
