//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOET_HMI
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_orderarchiv
    {
        public long id { get; set; }
        public string sParamsetName { get; set; }
        public int iQuantityTarget { get; set; }
        public int iQuantityDone { get; set; }
        public int iCartonQuantProPallet { get; set; }
        public int iCartonDone { get; set; }
        public string sAddedByToQueue { get; set; }
        public System.DateTime dtAddedOnToQueue { get; set; }
        public System.DateTime dtLoadedToPLCOn { get; set; }
        public Nullable<System.DateTime> dtStartedOn { get; set; }
        public Nullable<System.DateTime> dtFinishedOn { get; set; }
        public Nullable<System.DateTime> dtCancelledOn { get; set; }
        public int iState { get; set; }
        public bool bActiveInPLC { get; set; }
    }
}
