//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOET_HMI
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_paramset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_paramset()
        {
            this.db_orderqueue = new HashSet<db_orderqueue>();
            this.db_parameter = new HashSet<db_parameter>();
        }
    
        public int id { get; set; }
        public string sName { get; set; }
        public int iType { get; set; }
        public System.DateTime dtCreatedOn { get; set; }
        public string sCreatedBy { get; set; }
        public System.DateTime dtLastModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_orderqueue> db_orderqueue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_parameter> db_parameter { get; set; }
    }
}
