//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOET_HMI
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_parameterlog
    {
        public long id { get; set; }
        public System.DateTime dtTime { get; set; }
        public string sOldValue { get; set; }
        public string sNewValue { get; set; }
        public string sParamSetName { get; set; }
        public string sParamSetType { get; set; }
        public string sParameterName { get; set; }
        public string sAction { get; set; }
        public string sUserName { get; set; }
    }
}
